#!/usr/bin/env python3
"""png_to_rgb565.py — 像素鱼 RGBA PNG → RGB565 C 数组（fish_sprites.h）

- 输入 assets/fish/fish_N.png（RGBA，birefnet 去背景后）
- 缩放到 96x96（LANCZOS）；alpha < 128 → 透明键 0xF81F（品红，鱼图黑描边不能用黑键）
- 输出 firmware/src/fish_sprites.h：
    const uint16_t fish_N[96*96] PROGMEM  × 7
    const uint16_t* const FISH_SPRITES[7]  索引表
- M5GFX/LovyanGFX 的 pushImage 按 host order 读 uint16 内存数组（ESP32 小端原生），
  因此数组直接存 RGB565 原生值（0xF800=红）；swapBytes 只影响 SPI 传输不用于此。
- 附加 --check：把 fish_0 数组回渲成 PNG 抽查颜色/透明键。
"""
import sys
from pathlib import Path

from PIL import Image

SIZE = 96
TRANSPARENT_KEY = 0xF81F  # magenta
FISH_COUNT = 7

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "fish"
OUT = ROOT / "firmware" / "src" / "fish_sprites.h"


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(png: Path) -> list[int]:
    im = Image.open(png).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    px = im.load()
    out = []
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            if a < 128:
                out.append(TRANSPARENT_KEY)
            else:
                out.append(rgb565(r, g, b))
    return out


def main() -> None:
    arrays = []
    for n in range(FISH_COUNT):
        png = SRC / f"fish_{n}.png"
        if not png.exists():
            sys.exit(f"missing {png}")
        data = convert(png)
        arrays.append(data)
        n_trans = sum(1 for v in data if v == TRANSPARENT_KEY)
        print(f"fish_{n}: {len(data)} px, transparent {n_trans} ({n_trans/len(data):.0%})")

    lines = [
        "// Auto-generated by tools/png_to_rgb565.py — do not edit.",
        "// 96x96 RGB565 pixel-fish sprites; transparent key 0xF81F (magenta).",
        "// Native host-order uint16 values (0xF800 = red) for M5GFX pushImage.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <pgmspace.h>",
        "",
        f"#define FISH_SPRITE_SIZE {SIZE}",
        f"#define FISH_SPRITE_COUNT {FISH_COUNT}",
        f"#define FISH_TRANSPARENT_KEY 0xF81F",
        "",
    ]
    for n, data in enumerate(arrays):
        lines.append(f"const uint16_t fish_{n}[{SIZE * SIZE}] PROGMEM = {{")
        for i in range(0, len(data), 12):
            chunk = ", ".join(f"0x{v:04X}" for v in data[i : i + 12])
            lines.append("    " + chunk + ",")
        lines.append("};")
        lines.append("")
    lines.append(
        f"const uint16_t* const FISH_SPRITES[FISH_SPRITE_COUNT] = {{"
        + ", ".join(f"fish_{n}" for n in range(FISH_COUNT))
        + "};"
    )
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")

    if "--check" in sys.argv:
        # 回渲 fish_0：RGB565 → RGB，透明键 → 品红，供人工抽查
        data = arrays[0]
        im = Image.new("RGB", (SIZE, SIZE))
        for i, v in enumerate(data):
            if v == TRANSPARENT_KEY:
                im.putpixel((i % SIZE, i // SIZE), (255, 0, 255))
            else:
                r = ((v >> 11) & 0x1F) * 255 // 31
                g = ((v >> 5) & 0x3F) * 255 // 63
                b = (v & 0x1F) * 255 // 31
                im.putpixel((i % SIZE, i // SIZE), (r, g, b))
        check = SRC / "fish_0_check.png"
        im.save(check)
        print(f"check render: {check}")


if __name__ == "__main__":
    main()
