; RollerCAN 力反馈旋钮 Demo — M5Stack CoreS3
; 依赖自动通过 lib_deps 拉取，无需手动安装
[env:m5stack-cores3]
platform = espressif32@6.7.0
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    m5stack/M5Unified@^0.2.5
    m5stack/M5GFX@^0.2.7
    https://github.com/m5stack/M5Unit-Roller.git
